name: Simple CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: false
        default: 'default'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a simple command
        run: |
          set -e
          echo "Hello, this is a simple CI pipeline!"
          mvn -v
          pwd
          java -v
          mvn exec:java -DargFromCommandLine="src/main/resources/input.txt"
          
